version: '3'

services:

  servidor_dns:
    build: .
    container_name: servidor_dns
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      rede_trabalho:
        ipv4_address: 172.30.0.53

  servidor_web:
    build: .
    container_name: servidor_web
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      rede_trabalho:
        ipv4_address: 172.30.0.10

  cliente_web:
    build: .
    container_name: cliente_web
    tty: true
    cap_add:
      - NET_ADMIN
    networks:
      rede_trabalho:
        ipv4_address: 172.30.0.20

networks:
  rede_trabalho:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24